server:
  port: 9191


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/horizon_hotel_db
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true

  servelet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 2KB